version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file: ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - fortify-net

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: ./backend/.env.production
    depends_on:
      - mongodb
      - redis
    networks:
      - fortify-net

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - fortify-net

  redis:
    image: redis
    container_name: redis
    networks:
      - fortify-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - fortify-net

volumes:
  mongo-data:

networks:
  fortify-net:
    driver: bridge
