version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fortify-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - fortify-net
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    container_name: fortify-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - fortify-net

  nginx:
    image: nginx:alpine
    container_name: fortify-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - fortify-net

  mongo:
    image: mongo
    container_name: fortify-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - fortify-net

  redis:
    image: redis:7-alpine
    container_name: fortify-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fortify-net

volumes:
  mongo-data:
  redis-data:

networks:
  fortify-net:
