version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: ./backend/.env.production
    depends_on:
      - mongo
      - redis
    networks:
      - fortify-net
    expose:
      - 5000

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - fortify-net

  redis:
    image: redis:7
    container_name: redis
    networks:
      - fortify-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - fortify-net

volumes:
  mongo_data:

networks:
  fortify-net:
    driver: bridge
